packages:
  - "apps/*"
  - "packages/*"
  - "packages/@atomiton/*"

catalog:
  # React and related types
  react: ^19.1.1
  react-dom: ^19.1.1
  "@types/react": ^19.1.13
  "@types/react-dom": ^19.1.9

  # Testing libraries
  "@testing-library/jest-dom": ^6.4.2
  "@testing-library/react": ^16.3.0
  vitest: ^2.1.9
  "@vitest/ui": ^2.1.9
  jsdom: ^24.0.0

  # Build tools
  vite: ^7.1.5
  "@vitejs/plugin-react": ^5.0.2
  vite-plugin-dts: ^4.5.4
  rollup-plugin-visualizer: ^6.0.3
  terser: ^5.44.0

  # TypeScript and linting
  typescript: ^5.9.2
  eslint: ^9.35.0

  # Node types
  "@types/node": ^20.19.14
