packages:
  - "apps/*"
  - "packages/*"
  - "packages/@atomiton/*"

onlyBuiltDependencies:
  - "lefthook"

catalog:
  # React and related types
  react: ^19.1.1
  react-dom: ^19.1.1
  "@types/react": ^19.1.13
  "@types/react-dom": ^19.1.9

  # Testing libraries
  "@testing-library/jest-dom": ^6.8.0
  "@testing-library/react": ^16.3.0
  "@testing-library/user-event": ^14.6.1
  vitest: ^3.2.4
  "@vitest/ui": ^3.2.4
  "@vitest/coverage-v8": ^3.2.4
  jsdom: ^25.0.1

  # Build tools
  vite: ^7.1.5
  "@vitejs/plugin-react": ^5.0.2
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^5.1.4
  rollup-plugin-visualizer: ^6.0.3
  terser: ^5.44.0
  "@tailwindcss/vite": ^4.1.12
  tailwindcss: ^4.1.13

  # TypeScript and linting
  typescript: ^5.9.2
  eslint: ^9.35.0

  # Node types
  "@types/node": ^20.19.14

  # Development tools
  prettier: ^3.6.2
  kill-port: ^2.0.1

  # Validation and data
  zod: ^3.25.3

  # Additional tooling dependencies
  cross-env: ^10.0.0
  knip: ^5.63.1
  lint-staged: ^16.1.6
  playwright: ^1.55.0
  "@playwright/test": ^1.55.0
  tsx: ^4.20.5
  turbo: ^2.5.8
