export const content = [
  {
    id: "550e8400-e29b-41d4-a716-446655440001",
    title: "Hello World",
    category: "Blueprint Templates",
    image: "/images/gallery/1.jpg",
    type: "blueprint",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440002",
    title: "Data Transform Pipeline",
    category: "Blueprint Templates",
    image: "/images/gallery/2.jpg",
    type: "blueprint",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440003",
    title: "Image Processing Workflow",
    category: "Blueprint Templates",
    image: "/images/gallery/3.jpg",
    type: "blueprint",
  },
  {
    id: 3,
    title: "Futuristic Humanoid Robot Test",
    category: "Untitled Folder",
    image: "/images/scenes/1.jpg",
    type: "image",
  },
  {
    id: 4,
    title: "Gas Station Icon 1.0",
    category: "Untitled Folder",
    image: "/images/scenes/2.jpg",
    type: "video",
  },
  {
    id: 5,
    title: "Classic Car in Studio",
    category: "3D Icons",
    image: "/images/scenes/3.jpg",
    type: "image",
  },
  {
    id: 6,
    title: "Artisanal Food Arrangement",
    category: "Untitled Folder",
    image: "/images/scenes/4.jpg",
    type: "video",
  },
  {
    id: 7,
    title: "Delivery Robot on Wheels",
    category: "Untitled Folder",
    image: "/images/scenes/5.jpg",
    type: "image",
  },
  {
    id: 8,
    title: "Minimalist Architecture Scene",
    category: "Untitled Folder",
    image: "/images/scenes/6.jpg",
    type: "video",
  },
  {
    id: 9,
    title: "Animated Girl with Headphones",
    category: "3D Icons",
    image: "/images/scenes/7.jpg",
    type: "image",
  },
  {
    id: 10,
    title: "Cute Shop Storefront Icon",
    category: "Untitled Folder",
    image: "/images/scenes/8.jpg",
    type: "image",
  },
  {
    id: 11,
    title: "Cute Shop Storefront Icon",
    category: "Untitled Folder",
    image: "/images/scenes/9.jpg",
    type: "video",
  },
  {
    id: 12,
    title: "Cute Shop Storefront Icon",
    category: "Untitled Folder",
    image: "/images/scenes/10.jpg",
    type: "image",
  },
  {
    id: 13,
    title: "Animated Girl with Headphones",
    category: "Untitled Folder",
    image: "/images/scenes/11.jpg",
    type: "image",
  },
  {
    id: 14,
    title: "Cute Shop Storefront Icon",
    category: "3D Icons",
    image: "/images/scenes/12.jpg",
    type: "image",
  },
];
