/**
 * Standard error codes for execution failures
 */
export enum ErrorCode {
  // Validation errors
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INVALID_PARAMETERS = "INVALID_PARAMETERS",
  INVALID_NODE = "INVALID_NODE",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  TYPE_MISMATCH = "TYPE_MISMATCH",

  // Execution errors
  EXECUTION_FAILED = "EXECUTION_FAILED",
  NODE_NOT_FOUND = "NODE_NOT_FOUND",
  NODE_TYPE_NOT_FOUND = "NODE_TYPE_NOT_FOUND",
  IMPLEMENTATION_NOT_FOUND = "IMPLEMENTATION_NOT_FOUND",
  CIRCULAR_DEPENDENCY = "CIRCULAR_DEPENDENCY",
  NO_EXECUTOR_FACTORY = "NO_EXECUTOR_FACTORY",

  // Runtime errors
  TIMEOUT = "TIMEOUT",
  CANCELLED = "CANCELLED",
  MEMORY_LIMIT_EXCEEDED = "MEMORY_LIMIT_EXCEEDED",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  // Transport errors
  TRANSPORT_ERROR = "TRANSPORT_ERROR",
  NO_TRANSPORT = "NO_TRANSPORT",
  IPC_COMMUNICATION_FAILED = "IPC_COMMUNICATION_FAILED",
  SERIALIZATION_FAILED = "SERIALIZATION_FAILED",
  DESERIALIZATION_FAILED = "DESERIALIZATION_FAILED",

  // System errors
  INTERNAL_ERROR = "INTERNAL_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
