name: Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel in-progress runs on new push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Single build job - runs once, shared by all test jobs
  build:
    name: Build All Packages
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.base_ref || github.ref_name }}-
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build all packages
        run: pnpm exec turbo run build --cache-dir=.turbo

      - name: Cache workspace
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            packages/@atomiton/*/node_modules
            packages/@atomiton/*/dist
            apps/*/node_modules
            apps/*/dist
            .turbo
          key: workspace-${{ github.sha }}

  # Fast feedback: Run critical tests first
  critical-tests:
    name: Critical Tests (Fast Fail)
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore workspace
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            packages/@atomiton/*/node_modules
            packages/@atomiton/*/dist
            apps/*/node_modules
            apps/*/dist
            .turbo
          key: workspace-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Run critical tests
        run: pnpm exec turbo run test --cache-dir=.turbo -- -- -t "critical:"

      - name: Upload critical test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: critical-test-results
          path: |
            **/test-results/
            **/.vitest-cache/

  # Full unit test suite (runs after critical tests pass)
  unit-tests:
    name: Full Unit Test Suite
    runs-on: ubuntu-latest
    needs: critical-tests
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore workspace
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            packages/@atomiton/*/node_modules
            packages/@atomiton/*/dist
            apps/*/node_modules
            apps/*/dist
            .turbo
          key: workspace-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Run all unit tests
        run: pnpm exec turbo run test --cache-dir=.turbo

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: |
            **/test-results/
            **/.vitest-cache/

  # Integration tests (only runs if unit tests pass)
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore workspace
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            packages/@atomiton/*/node_modules
            packages/@atomiton/*/dist
            apps/*/node_modules
            apps/*/dist
            .turbo
          key: workspace-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Run integration tests
        run: pnpm exec turbo run test:integration --cache-dir=.turbo

      - name: Upload integration test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: |
            **/test-results/
            **/coverage/

  # E2E tests (final gate - only runs if integration tests pass)
  e2e-tests:
    name: E2E Tests (Shard ${{ matrix.shardIndex }}/${{ matrix.shardTotal }})
    runs-on: ubuntu-latest
    needs: integration-tests
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore workspace
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            packages/@atomiton/*/node_modules
            packages/@atomiton/*/dist
            apps/*/node_modules
            apps/*/dist
            .turbo
          key: workspace-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Get Playwright version
        id: playwright-version
        run: |
          VERSION=$(pnpm --filter @atomiton/e2e list --depth=-1 --json 2>/dev/null | jq -r '.[] | select(.name=="playwright") | .version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key:
            ${{ runner.os }}-playwright-${{
            steps.playwright-version.outputs.version }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run:
          pnpm --filter @atomiton/e2e exec playwright install --with-deps
          chromium

      - name:
          Run E2E tests (Shard ${{ matrix.shardIndex }}/${{ matrix.shardTotal
          }})
        run:
          pnpm --filter @atomiton/e2e exec playwright test --shard=${{
          matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          CI: true
          PLAYWRIGHT_HEADED: false

      - name: Upload E2E test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-${{ matrix.shardIndex }}
          path: |
            **/test-results/
            **/playwright-report/
